name: Build docker image
on:
  push:
    branches: [ main ]

jobs:
  buildDockerimage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t counterappdockerfile .
  
  launchFlyIoApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Launch FlyIo App
        run: flyctl launch --now --dockerfile Dockerfile